# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbAOm7YOxes7kUm9O_PJzEdoqfRXZXmJ
"""

def create_planilha():
  from openpyxl import load_workbook, Workbook
  planilha_teste01 = Workbook()
  pagina1 = planilha_teste01.active
  with open ('teste1','r',encoding= 'utf-8') as arquivo:
        for linha in arquivo:
            pagina1.append(linha.split (','))

  planilha_teste01.save('teste2.xlsx')
create_planilha()